export const Colors = {

  black: "#121214",
  darkgrey: "#3A3A3D",
  grey: "#818384",
  trueGrey: "#4b4b4b",
  lightgrey: "#D7DADC",
  primary: "#48f2124E",
  secondary: "#e3971280",
  blue: "0000ff",
  opacityBlue: "#0000ff1",
  opacityGrey: "#33333380",
  white: "#ffffff",
  blue: "#0000FF",
  red:'#d50a0e',
  darkBlue:'#0f1222',
  trueBlack: "#000000",
  darkPurple:"#220f18",
  purple:"#f11e64",

};

export const navigationImages = {
    home_aktiv: require('../assets/images/navigationImages/home-aktiv.png'),
    home_inaktiv: require('../assets/images/navigationImages/home-inaktiv.png'),

    newsfeed_aktiv: require('../assets/images/navigationImages/newsfeed- aktiv.png'),
    newsfeed_inaktiv: require('../assets/images/navigationImages/newsfeed-inaktiv.png'),

    leaderboard_aktiv: require('../assets/images/navigationImages/leaderboard-aktiv.png'),
    leaderboard_inaktiv: require('../assets/images/navigationImages/leaderboard-inaktiv.png'),

    draft_aktiv: require('../assets/images/navigationImages/draft-aktiv.png'),
    draft_inaktiv: require('../assets/images/navigationImages/draft-inkativ.png'),

    shop_aktiv: require('../assets/images/navigationImages/shop-aktiv.png'),
    shop_inaktiv: require('../assets/images/navigationImages/shop-inaktiv.png'),

////////////////

    choose_department: require('../assets/images/navigationImages/fomenusor-choose-gomb.png'),
    
    armory_button: require('../assets/images/navigationImages/armor-gomb.png'),
    energy_button: require('../assets/images/navigationImages/energy-gomb.png'),
    weaponry_button: require('../assets/images/navigationImages/weaponry-gomb.png'),
    cybercore_button: require('../assets/images/navigationImages/cybercore-gomb.png'),

////////////////

    signUp: require('../assets/images/navigationImages/REACT-kezdolap-signup-gom.png'),
    tutorial: require('../assets/images/navigationImages/REACT-kezdolap-tutorial-gom.png'),

    tutorialBackground: require('../assets/images/navigationImages/ESCom-mobilos-concept-trial-mode.png'),

};

export const IMAGES = {
    home_background: require('../assets/images/escom titan hatter.png'),
    welcome_background: require('../assets/images/navigationImages/REACT-kezdolap.png'),
    logo: require('../assets/escomicon.png'),
    escoin_image: require('../assets/images/escoin-icon.png'),
    estimatedRTO_image: require('../assets/images/RTO-hatter.png')

};

export const ArmorImages = {
  hatterKepArmor: require('../gombok/escom_mobil gombok_hatter1.png'),
  gomb1: require('../gombok/gomb1.png'),
  gomb2: require('../gombok/gomb2.png'),
  gomb3: require('../gombok/gomb3.png'),
  gomb4: require('../gombok/gomb4.png'),
  gomb5: require('../gombok/gomb5.png'),
  gomb6: require('../gombok/gomb6.png'),
  gomb7: require('../gombok/gomb7.png'),
  gomb8: require('../gombok/gomb8.png'),
  gomb9: require('../gombok/gomb9.png'),
  gomb10: require('../gombok/gomb10.png'),
  gomb11: require('../gombok/gomb11.png'),
  gomb12: require('../gombok/gomb12.png'),
  gomb13: require('../gombok/gomb13.png'),
  gomb14: require('../gombok/gomb14.png'),
  gomb15: require('../gombok/gomb15.png'),
  gomb16: require('../gombok/gomb16.png'),
  gombClear: require('../gombok/clear_gomb.png'),
  gombAnalyze: require('../gombok/analyze_gomb.png'),

};

export const WeaponImages = {
  hatterKepWeapon: require('../gombok/Weaponry/escom-mobil-gombokuj-nagy-hatter-weaponry.png'),
  gomb1: require('../gombok/Weaponry/gomb-1.png'),
  gomb2: require('../gombok/Weaponry/gomb-2.png'),
  gomb3: require('../gombok/Weaponry/gomb-3.png'),
  gomb4: require('../gombok/Weaponry/gomb-4.png'),
  gomb5: require('../gombok/Weaponry/gomb-5.png'),
  gomb6: require('../gombok/Weaponry/gomb-6.png'),
  gomb7: require('../gombok/Weaponry/gomb-7.png'),
  gomb8: require('../gombok/Weaponry/gomb-8.png'),
  gomb9: require('../gombok/Weaponry/gomb-9.png'),
  gomb10: require('../gombok/Weaponry/gomb-10.png'),
  gomb11: require('../gombok/Weaponry/gomb-11.png'),
  gomb12: require('../gombok/Weaponry/gomb-12.png'),
  gomb13: require('../gombok/Weaponry/gomb-13.png'),
  gomb14: require('../gombok/Weaponry/gomb14.png'),
  gomb15: require('../gombok/Weaponry/gomb-15.png'),
  gomb16: require('../gombok/Weaponry/gomb-16.png'),
  
};

//////////////////////////////////////////////////////////////

export const LeaderboardImages = {
  armorLeaderBoard: require('../assets/images/LeaderBoardImages/ARMOR-LEADERBOARD-HEADER.png'),
  showAll: require('../assets/images/LeaderBoardImages//SHOW-ME-ALL.png'),
  myLocation: require('../assets/images/LeaderBoardImages/MY-LOCATION.png'),
  
};

////////////////////////////////////////////////////////////////

export const Musics  = {
  backgroundMusic: require('../assets/Music/Background_music_(Extrahuman).mp3'),
  click: require('../assets/Music/Touch_Sound_Effect.mp3'),
  armoryBgMusic: require('../assets/Music/ArmoryBackgroundMusic.mp3'),

};

export const profileImages = {

  screenBackground: require('../assets/images/Profile/profil-háttér.png'),
  keret: require('../assets/images/Profile/profil-keret.png'),
  achievement: require('../assets/images/Profile/profil-achi-gomb.png'),
  back: require('../assets/images/Profile/profil-back-to-home-gomb.png'),
  blankProfilePicture: require('../assets/images/Profile/profil-kepkeret.png'),
};

export const shopImages = {
    screenBackground: require('../assets/images/ShopImages/escom-mobil-gombok-shop-hater.png'),
    header: require('../assets/images/ShopImages/shop-header.png'),
    logo: require('../assets/images/ShopImages/escom-header-logo.png'),
    button: require('../assets/images/ShopImages/схоп-гиве-ме-монеѕ.png'),

};

export const countries = {
  "AF": "Afghanistan",
  "AX": "Aland Islands",
  "AL": "Albania",
  "DZ": "Algeria",
  "AS": "American Samoa",
  "AD": "Andorra",
  "AO": "Angola",
  "AI": "Anguilla",
  "AQ": "Antarctica",
  "AG": "Antigua And Barbuda",
  "AR": "Argentina",
  "AM": "Armenia",
  "AW": "Aruba",
  "AU": "Australia",
  "AT": "Austria",
  "AZ": "Azerbaijan",
  "BS": "Bahamas",
  "BH": "Bahrain",
  "BD": "Bangladesh",
  "BB": "Barbados",
  "BY": "Belarus",
  "BE": "Belgium",
  "BZ": "Belize",
  "BJ": "Benin",
  "BM": "Bermuda",
  "BT": "Bhutan",
  "BO": "Bolivia",
  "BA": "Bosnia And Herzegovina",
  "BW": "Botswana",
  "BV": "Bouvet Island",
  "BR": "Brazil",
  "IO": "British Indian Ocean Territory",
  "BN": "Brunei Darussalam",
  "BG": "Bulgaria",
  "BF": "Burkina Faso",
  "BI": "Burundi",
  "KH": "Cambodia",
  "CM": "Cameroon",
  "CA": "Canada",
  "CV": "Cape Verde",
  "KY": "Cayman Islands",
  "CF": "Central African Republic",
  "TD": "Chad",
  "CL": "Chile",
  "CN": "China",
  "CX": "Christmas Island",
  "CC": "Cocos (Keeling) Islands",
  "CO": "Colombia",
  "KM": "Comoros",
  "CG": "Congo",
  "CD": "Congo, Democratic Republic",
  "CK": "Cook Islands",
  "CR": "Costa Rica",
  "CI": "Cote D\"Ivoire",
  "HR": "Croatia",
  "CU": "Cuba",
  "CY": "Cyprus",
  "CZ": "Czech Republic",
  "DK": "Denmark",
  "DJ": "Djibouti",
  "DM": "Dominica",
  "DO": "Dominican Republic",
  "EC": "Ecuador",
  "EG": "Egypt",
  "SV": "El Salvador",
  "GQ": "Equatorial Guinea",
  "ER": "Eritrea",
  "EE": "Estonia",
  "ET": "Ethiopia",
  "FK": "Falkland Islands (Malvinas)",
  "FO": "Faroe Islands",
  "FJ": "Fiji",
  "FI": "Finland",
  "FR": "France",
  "GF": "French Guiana",
  "PF": "French Polynesia",
  "TF": "French Southern Territories",
  "GA": "Gabon",
  "GM": "Gambia",
  "GE": "Georgia",
  "DE": "Germany",
  "GH": "Ghana",
  "GI": "Gibraltar",
  "GR": "Greece",
  "GL": "Greenland",
  "GD": "Grenada",
  "GP": "Guadeloupe",
  "GU": "Guam",
  "GT": "Guatemala",
  "GG": "Guernsey",
  "GN": "Guinea",
  "GW": "Guinea-Bissau",
  "GY": "Guyana",
  "HT": "Haiti",
  "HM": "Heard Island & Mcdonald Islands",
  "VA": "Holy See (Vatican City State)",
  "HN": "Honduras",
  "HK": "Hong Kong",
  "HU": "Hungary",
  "IS": "Iceland",
  "IN": "India",
  "ID": "Indonesia",
  "IR": "Iran, Islamic Republic Of",
  "IQ": "Iraq",
  "IE": "Ireland",
  "IM": "Isle Of Man",
  "IL": "Israel",
  "IT": "Italy",
  "JM": "Jamaica",
  "JP": "Japan",
  "JE": "Jersey",
  "JO": "Jordan",
  "KZ": "Kazakhstan",
  "KE": "Kenya",
  "KI": "Kiribati",
  "KR": "Korea",
  "KP": "North Korea",
  "KW": "Kuwait",
  "KG": "Kyrgyzstan",
  "LA": "Lao People\"s Democratic Republic",
  "LV": "Latvia",
  "LB": "Lebanon",
  "LS": "Lesotho",
  "LR": "Liberia",
  "LY": "Libyan Arab Jamahiriya",
  "LI": "Liechtenstein",
  "LT": "Lithuania",
  "LU": "Luxembourg",
  "MO": "Macao",
  "MK": "Macedonia",
  "MG": "Madagascar",
  "MW": "Malawi",
  "MY": "Malaysia",
  "MV": "Maldives",
  "ML": "Mali",
  "MT": "Malta",
  "MH": "Marshall Islands",
  "MQ": "Martinique",
  "MR": "Mauritania",
  "MU": "Mauritius",
  "YT": "Mayotte",
  "MX": "Mexico",
  "FM": "Micronesia, Federated States Of",
  "MD": "Moldova",
  "MC": "Monaco",
  "MN": "Mongolia",
  "ME": "Montenegro",
  "MS": "Montserrat",
  "MA": "Morocco",
  "MZ": "Mozambique",
  "MM": "Myanmar",
  "NA": "Namibia",
  "NR": "Nauru",
  "NP": "Nepal",
  "NL": "Netherlands",
  "AN": "Netherlands Antilles",
  "NC": "New Caledonia",
  "NZ": "New Zealand",
  "NI": "Nicaragua",
  "NE": "Niger",
  "NG": "Nigeria",
  "NU": "Niue",
  "NF": "Norfolk Island",
  "MP": "Northern Mariana Islands",
  "NO": "Norway",
  "OM": "Oman",
  "PK": "Pakistan",
  "PW": "Palau",
  "PS": "Palestinian Territory, Occupied",
  "PA": "Panama",
  "PG": "Papua New Guinea",
  "PY": "Paraguay",
  "PE": "Peru",
  "PH": "Philippines",
  "PN": "Pitcairn",
  "PL": "Poland",
  "PT": "Portugal",
  "PR": "Puerto Rico",
  "QA": "Qatar",
  "RE": "Reunion",
  "RO": "Romania",
  "RU": "Russian Federation",
  "RW": "Rwanda",
  "BL": "Saint Barthelemy",
  "SH": "Saint Helena",
  "KN": "Saint Kitts And Nevis",
  "LC": "Saint Lucia",
  "MF": "Saint Martin",
  "PM": "Saint Pierre And Miquelon",
  "VC": "Saint Vincent And Grenadines",
  "WS": "Samoa",
  "SM": "San Marino",
  "ST": "Sao Tome And Principe",
  "SA": "Saudi Arabia",
  "SN": "Senegal",
  "RS": "Serbia",
  "SC": "Seychelles",
  "SL": "Sierra Leone",
  "SG": "Singapore",
  "SK": "Slovakia",
  "SI": "Slovenia",
  "SB": "Solomon Islands",
  "SO": "Somalia",
  "ZA": "South Africa",
  "GS": "South Georgia And Sandwich Isl.",
  "ES": "Spain",
  "LK": "Sri Lanka",
  "SD": "Sudan",
  "SR": "Suriname",
  "SJ": "Svalbard And Jan Mayen",
  "SZ": "Swaziland",
  "SE": "Sweden",
  "CH": "Switzerland",
  "SY": "Syrian Arab Republic",
  "TW": "Taiwan",
  "TJ": "Tajikistan",
  "TZ": "Tanzania",
  "TH": "Thailand",
  "TL": "Timor-Leste",
  "TG": "Togo",
  "TK": "Tokelau",
  "TO": "Tonga",
  "TT": "Trinidad And Tobago",
  "TN": "Tunisia",
  "TR": "Turkey",
  "TM": "Turkmenistan",
  "TC": "Turks And Caicos Islands",
  "TV": "Tuvalu",
  "UG": "Uganda",
  "UA": "Ukraine",
  "AE": "United Arab Emirates",
  "GB": "United Kingdom",
  "US": "United States",
  "UM": "United States Outlying Islands",
  "UY": "Uruguay",
  "UZ": "Uzbekistan",
  "VU": "Vanuatu",
  "VE": "Venezuela",
  "VN": "Vietnam",
  "VG": "Virgin Islands, British",
  "VI": "Virgin Islands, U.S.",
  "WF": "Wallis And Futuna",
  "EH": "Western Sahara",
  "YE": "Yemen",
  "ZM": "Zambia",
  "ZW": "Zimbabwe"
}