import { StyleSheet } from "react-native";
import { Colors } from "./Constants";

export default StyleSheet.create({
 
  container: {
    position: 'relative',
    backgroundColor: Colors.black,
    alignItems: 'center',
    justifyContent: 'center',
    height: '100%',
    width: '100%',
  },
  backGroundImage: {
    display: 'flex',
    position: 'absolute',
    margin: 'auto',
    height: '100%',
    width: '100%',
    resizeMode: 'cover',
    // borderColor: colors.white,
    // borderWidth: 1,

  },
  felsoKeret: {
      position: 'relative',
      height: '31.6%',     // billentyizet magassag
   
      paddingTop: 2,
      
      display: 'flex',
      //borderWidth: 1, 
      borderColor: Colors.grey,
      flexDirection: 'row',
      alignItems: 'center',
      alignContent: 'center',
      elevation: 3,
      width: '100%',
      resizeMode: 'stretch',
      justifyContent: 'center',
      flexDirection: 'column',

      zIndex: 10,

  },
  modal: {
    backgroundColor: "#00000050",
    justifyContent: 'center',
    alignSelf: 'center',
    alignItems: 'center',
    flex: 1,
    // borderWidth:1,
    // borderColor: Colors.white,
    position: 'relative',
    height: "60%",
    width: "100%",
  },
  modalText: {
    letterSpacing: 3,
    fontSize: 18,
    marginTop: 20,
    color: Colors.white,
    alignSelf: 'center',
    //justifyContent: 'center',
    textAlign: 'center',
  },
  modalButton: {
    //flex: 1,
    width: "75%",
    height: 70,
   // maxHeight: "10%",
    alignSelf: 'center',
    marginTop: 20,
    borderRadius: 10,
    borderWidth: 2,
    borderColor: Colors.darkgrey,
    backgroundColor: Colors.black,

  },
  szinezettGomsorKeret: {
    
    position: 'relative',
      //marginLeft: 44,
      //marginRight: 44,
      height: '25%',
      display: 'flex',
      // borderWidth: 1,
     
      borderColor: Colors.grey,
      flexDirection: 'row',
      alignItems: 'center',
      alignSelf: 'center',
      resizeMode: 'stretch',
      elevation: 3,
      aspectRatio: 6,
     
      maxWidth: "90%",
      flexWrap: "wrap",
      alignItems: 'center',
      alignContent: 'center',
      zIndex: 12,

    marginBottom: "3%",
    

  },

  felsoGombSorKeret: {
      position: 'relative',
      //marginLeft: 44,
      //marginRight: 44,
      height: '25%',
      display: 'flex',
      // borderWidth: 1,
     
      borderColor: Colors.grey,
      flexDirection: 'row',
      alignItems: 'center',
      alignSelf: 'center',
      resizeMode: 'stretch',
      elevation: 3,
      aspectRatio: 6,
     
      maxWidth: "90%",
      flexWrap: "wrap",
      alignItems: 'center',
      alignContent: 'center',
      zIndex: 12,
    },
    
  felsoGombSorKeretPlaceholder: {
      position: 'absolute',
      //marginLeft: 44,
      //marginRight: 44,
      height: '25%',
      maxHeight: '25%',
      display: 'flex',
      //borderWidth: 1,
      marginBottom: "4%",
      borderColor: Colors.grey,
      flexDirection: 'row',
      alignItems: 'center',
      alignSelf: 'center',
      resizeMode: 'stretch',
      elevation: 3,
      width: '80%', 
      flexWrap: 'nowrap',
      alignItems: 'center',
      alignContent: 'center',
      zIndex: 12,
  },
  felsoIrkaloButtonKeret: {
    position: 'relative',
       // maxHeight: "110%", 
    aspectRatio: 1,
    width: "18.99%",   
    marginLeft: 2,
    marginLeft: 2,
    //display: 'flex',
    borderWidth: 2.5,
    borderColor: Colors.blue,
   // flex: 1,
    aspectRatio: 1,
    //justifyContent: 'space-evenly',  // gombok kozepen
    justifyContent: 'center',
    resizeMode: 'cover',
    flexWrap: 'nowrap',
    zIndex: 10,
  },
  felsoIrkaloButtonKeret_Weaponry: {
    position: 'relative',
       // maxHeight: "110%", 
    aspectRatio: 1,
    height: "50%", 
    marginBottom:"1%",  
    marginLeft: 2,
    marginLeft: 2,
    //display: 'flex',
    borderWidth: 2.5,
    borderColor: Colors.red,
   // flex: 1,
    aspectRatio: 1,
    //justifyContent: 'space-evenly',  // gombok kozepen
    justifyContent: 'center',
    resizeMode: 'cover',
    flexWrap: 'nowrap',
    zIndex: 10,
  },
  gombKeret: {
    position: 'relative',
    height: '100%',
    width: '100%',
    margin: "0.4%",
    borderWidth: 2,
    borderColor: Colors.blue,
    flex: 1,
    aspectRatio: 1,
    justifyContent: 'center',
  },
  assetCounter: {
    fontSize:12,
    color: Colors.white,
    alignSelf: 'flex-end',
    padding: "4%",
    position: 'absolute',
    zIndex: 20,
  },
  billentyuzetKeret: {
      position: 'relative',
      paddingTop: "0.4%",
      paddingBottom: "0.4%",

     // borderWidth: 1,
      borderColor: Colors.white,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      alignSelf: 'center',
      elevation: 10,
      width: '92%', 

      zIndex: 10,
  },
  alsoKeret: {
      position: 'relative',
      height: '13%',     //  magassag

      //aspectRatio: 3.2,
      paddingTop: 0,
      paddingBottom: 4,
      flexDirection: 'row',
      alignItems: 'center',
      elevation: 3,
      width: '100%',
      alignSelf: 'center',
      borderColor: Colors.white,
      //borderWidth: 1, 
      alignItems: 'center',
      justifyContent: 'center',

      zIndex: 10,
  },
  gombok: {
    position: 'relative',
    height: '100%',
    width: '100%',
    backgroundColor: Colors.opacityBlue,
  },
  alsoGombok: {
   // borderRadius: 50,
    borderColor: Colors.lightgrey,
    position: 'relative',
    width: '100%',
    height: '100%',
    backgroundColor: Colors.opacityBlue,
    //marginBottom: 10,
    borderColor: Colors.white,
    borderWidth: 0,

  },
  analyzeGombKeret: {
    position: 'relative',
    height: '90%',
    width: '100%',
    display: 'flex',
    marginLeft: 2,
    borderRadius: 50,
    // borderWidth: 0,
    // borderColor: colors.grey,
    flex: 1,
    // aspectRatio: 1,
    justifyContent: 'center',
  },
  clearGombKeret: {
    position: 'relative',
    height: '90%',
    width: '100%',
    display: 'flex',
    marginRight: 2,
    //display: 'flex',
    borderRadius: 50,
    // borderWidth: 0,
    // borderColor: colors.grey,
    flex: 1,
    //aspectRatio: 1,
    justifyContent: 'center',
  },
  gombKepek: {
    position: 'relative',
    resizeMode: 'stretch',
    width: '100%',
    height: '100%',
  },
  felsoGombKepek: {
    position: 'relative',
    resizeMode: 'stretch',
    width: '100%',
    height: '100%',
  },
  alsoGombKepek: {
    position: 'relative',
    resizeMode: 'stretch',
    width: '100%',
    height: '100%',    
  },
  shadowProp: {
    shadowColor: Colors.black,
    shadowOffset: {width: 2, height: -2},
    shadowOpacity: 0.3,
  },
  szoveg: {
    elevation: 3,
    position: 'relative',
    width: '100%',
    height: "50%",
    textAlign: 'center',

    // borderColor: Colors.white,
    // borderWidth: 1,

    fontSize: '3.2vw',
    fontWeight: 'bold',
    //fontFamily: 'LemonMilk',
    color: Colors.lightgrey,
    letterSpacing: 6,
    zIndex: 10,
    
  },


});